import type { Metadata } from "next";
import {Inter} from 'next/font/google';
import { Toaster } from "sonner";
import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";
import AuthProvider from "@/providers/auth-provider";
import { Navbar } from "@/components/common/navbar";
import { Footer } from "@/components/common/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <div className="main-layout">
            <Navbar/>
            <div className="children-container">
            {children}
            </div>
            <Footer/>
            </div>
            <Toaster richColors/>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
